export const USER_ACTIONS = {
    GET_USER_INFO_START: 'USER.GET_USER_INFO_START',
    GET_USER_INFO_FINISH: 'USER.GET_USER_INFO_FINISH',
    GET_USER_INFO_FAIL: 'USER.GET_USER_INFO_FAIL',

    USER_LOGIN_START: 'USER.USER_LOGIN_START',
    USER_LOGIN_FINISH: 'USER.USER_LOGIN_FINISH',
    USER_LOGIN_FAIL: 'USER.USER_LOGIN_FAIL',
};
